// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_w7-1nfmRuUlGtaLhePFLdCSNjwW824',
    appId: '1:513687934726:web:154509ba921b94d01bf087',
    messagingSenderId: '513687934726',
    projectId: 'todo-app-2027',
    authDomain: 'todo-app-2027.firebaseapp.com',
    storageBucket: 'todo-app-2027.firebasestorage.app',
    measurementId: 'G-QMRMC31PED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGuSK1xF3qaRdfvfsZp4q8nAEsxCo5W7w',
    appId: '1:513687934726:android:5041cc0df755fa1a1bf087',
    messagingSenderId: '513687934726',
    projectId: 'todo-app-2027',
    storageBucket: 'todo-app-2027.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWtTSMNjgoWn2jGQLKULLQzUyr6Z0Ebi0',
    appId: '1:513687934726:ios:38d16394174eecd71bf087',
    messagingSenderId: '513687934726',
    projectId: 'todo-app-2027',
    storageBucket: 'todo-app-2027.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );
}
